### ISSUE TITLE
Running as a production service

### ISSUE THREAD

**Issue by stefpiatek** [SAFEHR-data/PIXL#331]
### Definition of Done / Acceptance Criteria

- [x] UCLH-Foundry/PIXL#238
- [ ] UCLH-Foundry/PIXL#153
- [x] UCLH-Foundry/PIXL#305
- [ ] UCLH-Foundry/PIXL#193
- [ ] UCLH-Foundry/PIXL#310
- [ ] UCLH-Foundry/PIXL#290
- [x] UCLH-Foundry/PIXL#236
- [ ] UCLH-Foundry/PIXL#369
- [ ] UCLH-Foundry/PIXL#388
- [ ] UCLH-Foundry/PIXL#395
- [ ] UCLH-Foundry/PIXL#398
